version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: db-vidrelo-admin
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    networks:
      - vidrelo-admin-network
    volumes:
      - db-vidrelo-admin-volume:/data
    restart: unless-stopped

  app:
    container_name: vidrelo-admin-back
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - vidrelo-admin-network

networks:
  vidrelo-admin-network:
    name: vidrelo-admin-network

volumes:
  db-vidrelo-admin-volume:
    name: db-vidrelo-admin-volume
